"""empty message

Revision ID: 5d7be96c53ee
Revises: aec75c174acd
Create Date: 2024-09-22 12:21:27.374849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7be96c53ee'
down_revision = 'aec75c174acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmation_code', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmation_code')
    # ### end Alembic commands ###
